// upload photo videos constants

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const UPLOAD_MEDIA_REQUEST = 'UPLOAD_MEDIA_REQUEST';
export const UPLOAD_MEDIA_SUCCESS = 'UPLOAD_MEDIA_SUCCESS';
export const UPLOAD_MEDIA_FAILURE = 'UPLOAD_MEDIA_FAILURE';

export const CHECK_ALBUM_NAME_REQUEST = 'CHECK_ALBUM_NAME_REQUEST';
export const CHECK_ALBUM_NAME_SUCCESS = 'CHECK_ALBUM_NAME_SUCCESS';
export const CHECK_ALBUM_NAME_FAILURE = 'CHECK_ALBUM_NAME_FAILURE';


export const LIST_ALL_MEDIA_REQUEST = 'LIST_ALL_MEDIA_REQUEST';
export const LIST_ALL_MEDIA_SUCCESS = 'LIST_ALL_MEDIA_SUCCESS';
export const LIST_ALL_MEDIA_FAILURE = 'LIST_ALL_MEDIA_FAILURE';

export const LIST_ALBUM_REQUEST = 'LIST_ALBUM_REQUEST';
export const LIST_ALBUM_SUCCESS = 'LIST_ALBUM_SUCCESS';
export const LIST_ALBUM_FAILURE = 'LIST_ALBUM_FAILURE';

export const ADD_NEW_ALBUM_REQUEST = 'ADD_NEW_ALBUM_REQUEST';
export const ADD_NEW_ALBUM_SUCCESS = 'ADD_NEW_ALBUM_SUCCESS';
export const ADD_NEW_ALBUM_FAILURE = 'ADD_NEW_ALBUM_FAILURE';


export const MEDIA_LIST_BY_ITEM_REQUEST = 'MEDIA_LIST_BY_ITEM_REQUEST';
export const MEDIA_LIST_BY_ITEM_SUCCESS = 'MEDIA_LIST_BY_ITEM_SUCCESS';
export const MEDIA_LIST_BY_ITEM_FAILURE = 'MEDIA_LIST_BY_ITEM_FAILURE';

export const ALBUM_DETAIL_SUCCESS_LOCAL_DATA = 'ALBUM_DETAIL_SUCCESS_LOCAL_DATA';

export const LIST_PLANS_REQUEST = 'LIST_PLANS_REQUEST';
export const LIST_PLANS_SUCCESS = 'LIST_PLANS_SUCCESS';
export const LIST_PLANS_FAILURE = 'LIST_PLANS_FAILURE';

export const INVITED_USER_LIST_REQUEST = 'INVITED_USER_LIST_REQUEST';
export const INVITED_USER_LIST_SUCCESS = 'INVITED_USER_LIST_SUCCESS';
export const INVITED_USER_LIST_FAILURE = 'INVITED_USER_LIST_FAILURE';

export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST';
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
export const NOTIFICATION_LIST_FAILURE = 'NOTIFICATION_LIST_FAILURE';

export const SEND_APP_INVITATION_REQUEST = 'SEND_APP_INVITATION_REQUEST';
export const SEND_APP_INVITATION_SUCCESS = 'SEND_APP_INVITATION_SUCCESS';
export const SEND_APP_INVITATION_FAILURE = 'SEND_APP_INVITATION_FAILURE';
//// Auth constants

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

export const OWN_ALBUM_REQUEST = 'OWN_ALBUM_REQUEST';
export const OWN_ALBUM_SUCCESS = 'OWN_ALBUM_SUCCESS';
export const OWN_ALBUM_FAILURE = 'OWN_ALBUM_FAILURE';

export const OWN_ALBUM_SHARED_VIEW_REQUEST = 'OWN_ALBUM_SHARED_VIEW_REQUEST';
export const OWN_ALBUM_SHARED_VIEW_SUCCESS = 'OWN_ALBUM_SHARED_VIEW_SUCCESS';
export const OWN_ALBUM_SHARED_VIEW_FAILURE = 'OWN_ALBUM_SHARED_VIEW_FAILURE';

export const OWN_ALBUM_ALBUM_VIEW_REQUEST = 'OWN_ALBUM_ALBUM_VIEW_REQUEST';
export const OWN_ALBUM_ALBUM_VIEW_SUCCESS = 'OWN_ALBUM_ALBUM_VIEW_SUCCESS';
export const OWN_ALBUM_ALBUM_VIEW_FAILURE = 'OWN_ALBUM_ALBUM_VIEW_FAILURE';

export const SHARED_ALBUM_ALBUM_VIEW_REQUEST = 'SHARED_ALBUM_ALBUM_VIEW_REQUEST';
export const SHARED_ALBUM_ALBUM_VIEW_SUCCESS = 'SHARED_ALBUM_ALBUM_VIEW_SUCCESS';
export const SHARED_ALBUM_ALBUM_VIEW_FAILURE = 'SHARED_ALBUM_ALBUM_VIEW_FAILURE';

export const SHARED_ALBUM_REQUEST = 'SHARED_ALBUM_REQUEST';
export const SHARED_ALBUM_SUCCESS = 'SHARED_ALBUM_SUCCESS';
export const SHARED_ALBUM_FAILURE = 'SHARED_ALBUM_FAILURE';

export const GET_USER_SPACE_REQUEST = 'GET_USER_SPACE_REQUEST';
export const GET_USER_SPACE_SUCCESS = 'GET_USER_SPACE_SUCCESS';
export const GET_USER_SPACE_FAILURE = 'GET_USER_SPACE_FAILURE';

export const DELETE_USER_MEDIA_REQUEST = 'DELETE_USER_MEDIA_REQUEST';
export const DELETE_USER_MEDIA_SUCCESS = 'DELETE_USER_MEDIA_SUCCESS';
export const DELETE_USER_MEDIA_FAILURE = 'DELETE_USER_MEDIA_FAILURE';

export const DELETE_USER_MEDIA_ALBUM_DETAIL_REQUEST = 'DELETE_USER_MEDIA_ALBUM_DETAIL_REQUEST';
export const DELETE_USER_MEDIA_ALBUM_DETAIL_SUCCESS = 'DELETE_USER_MEDIA_ALBUM_DETAIL_SUCCESS';
export const DELETE_USER_MEDIA_ALBUM_DETAIL_FAILURE = 'DELETE_USER_MEDIA_ALBUM_DETAIL_FAILURE';


export const DELETE_ALBUM_REQUEST = 'DELETE_ALBUM_REQUEST';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_ALBUM_FAILURE = 'DELETE_ALBUM_FAILURE';
export const EDIT_EMAIL_REQUEST = 'EDIT_EMAIL_REQUEST';
export const EDIT_EMAIL_SUCCESS = 'EDIT_EMAIL_SUCCESS';
export const EDIT_EMAIL_FAILURE = 'EDIT_EMAIL_FAILURE';

export const UPDATE_ALBUM_NAME_REQUEST = 'UPDATE_ALBUM_NAME_REQUEST';
export const UPDATE_ALBUM_NAME__SUCCESS = 'UPDATE_ALBUM_NAME_SUCCESS';
export const UPDATE_ALBUM_NAME_FAILURE = 'UPDATE_ALBUM_NAME_FAILURE';

export const NOTIFICATION_SETTING_REQUEST = 'NOTIFICATION_SETTING_REQUEST';
export const NOTIFICATION_SETTING_SUCCESS = 'NOTIFICATION_SETTING_SUCCESS';
export const NOTIFICATION_SETTING_FAILURE = 'NOTIFICATION_SETTING_FAILURE';

export const UPDATE_INVITE_CODE_REQUEST = 'UPDATE_INVITE_CODE_REQUEST';
export const UPDATE_INVITE_CODE_SUCCESS = 'UPDATE_INVITE_CODE_SUCCESS';
export const UPDATE_INVITE_CODE_FAILURE = 'UPDATE_INVITE_CODE_FAILURE';

export const SUBSCRIBE_REQUEST = 'SUBSCRIBE_REQUEST';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE_FAILURE = 'SUBSCRIBE_FAILURE';

export const SHARE_ALBUM_TO_USER_REQUEST = 'SHARE_ALBUM_TO_USER_REQUEST';
export const SHARE_ALBUM_TO_USER_SUCCESS = 'SHARE_ALBUM_TO_USER_SUCCESS';
export const SHARE_ALBUM_TO_USER_FAILURE = 'SHARE_ALBUM_TO_USER_FAILURE';

export const SAVE_ALBUM_ID = "SAVE_ALBUM_ID";
export const SELECTED_REVOKED_USER = "SELECTED_REVOKED_USER";

export const ALBUM_LIST_OF_USER_REQUEST = 'ALBUM_LIST_OF_USER_REQUEST';
export const ALBUM_LIST_OF_USER_SUCCESS = 'ALBUM_LIST_OF_USER_SUCCESS';
export const ALBUM_LIST_OF_USER_FAILURE = 'ALBUM_LIST_OF_USER_FAILURE';

export const REVOKE_SHARE_ALBUM_REQUEST = 'REVOKE_SHARE_ALBUM_REQUEST';
export const REVOKE_SHARE_ALBUM_SUCCESS = 'REVOKE_SHARE_ALBUM_SUCCESS';
export const REVOKE_SHARE_ALBUM_FAILURE = 'REVOKE_SHARE_ALBUM_FAILURE';

// Upload Staging api and integration
export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

// Add new album upload img 
export const ADD_NEW_ALB_UPLOAD_IMAGE_REQUEST = 'ADD_NEW_ALB_UPLOAD_IMAGE_REQUEST';
export const ADD_NEW_ALB_UPLOAD_IMAGE_SUCCESS = 'ADD_NEW_ALB_UPLOAD_IMAGE_SUCCESS';
export const ADD_NEW_ALB_UPLOAD_IMAGE_FAILURE = 'ADD_NEW_ALB_UPLOAD_IMAGE_FAILURE';

// update existing album upload img 
export const UPDATE_ALB_UPLOAD_IMAGE_REQUEST = 'UPDATE_ALB_UPLOAD_IMAGE_REQUEST';
export const UPDATE_ALB_UPLOAD_IMAGE_SUCCESS = 'UPDATE_ALB_UPLOAD_IMAGE_SUCCESS';
export const UPDATE_ALB_UPLOAD_IMAGE_FAILURE = 'UPDATE_ALB_UPLOAD_IMAGE_FAILURE';


//
export const UPLOAD_ALBUM_IMAGE_REQUEST = 'UPLOAD_ALBUM_IMAGE_REQUEST';
export const UPLOAD_ALBUM_IMAGE_SUCCESS = 'UPLOAD_ALBUM_IMAGE_SUCCESS';
export const UPLOAD_ALBUM_IMAGE_FAILURE = 'UPLOAD_ALBUM_IMAGE_FAILURE';
