# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'OnlinePhotos' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'Firebase/Messaging'
  
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'OnlinePhotosTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'OnlinePhotos-tvOS' do
  # Pods for OnlinePhotos-tvOS

  target 'OnlinePhotos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
